import propTypes from "prop-types";
// Generated by https://quicktype.io

export const Rating = {
  rate: propTypes.number.isRequired,
  count: propTypes.number.isRequired,
};

export const Product = {
  id: propTypes.number.isRequired,
  title: propTypes.string.isRequired,
  price: propTypes.number.isRequired,
  description: propTypes.string.isRequired,
  category: propTypes.string.isRequired,
  image: propTypes.string.isRequired,
  rating: Rating,
};
export type Product = propTypes.InferProps<typeof Product>;
